# Generated by Django 5.2.3 on 2025-07-04 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('groceries', '0002_alter_grocerylist_name'), ('groceries', '0003_alter_grocerylist_name_and_more'), ('groceries', '0004_remove_grocerylist_unique_grocery_list_per_user_and_name_and_more')]

    dependencies = [
        ('groceries', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grocerylist',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AddConstraint(
            model_name='grocerylist',
            constraint=models.UniqueConstraint(condition=models.Q(('is_public', False)), fields=('username', 'name'), name='unique_grocery_list_per_user_and_name'),
        ),
        migrations.AddConstraint(
            model_name='grocerylist',
            constraint=models.UniqueConstraint(condition=models.Q(('is_public', True)), fields=('name',), name='unique_grocery_list_per_name'),
        ),
        migrations.RemoveConstraint(
            model_name='grocerylist',
            name='unique_grocery_list_per_user_and_name',
        ),
        migrations.RemoveConstraint(
            model_name='grocerylist',
            name='unique_grocery_list_per_name',
        ),
        migrations.AddConstraint(
            model_name='grocerylist',
            constraint=models.UniqueConstraint(condition=models.Q(('is_public', False)), fields=('username', 'name', 'is_public'), name='unique_grocery_list_per_user_and_name'),
        ),
        migrations.AddConstraint(
            model_name='grocerylist',
            constraint=models.UniqueConstraint(condition=models.Q(('is_public', True)), fields=('name', 'is_public'), name='unique_grocery_list_per_name'),
        ),
    ]
